name: test

on:
  schedule:
    - cron: '0 0 * * *' #UTC
  push:
    branches:
      - 'master'

jobs:
  composer:
    uses: kawax/composer-workflow/.github/workflows/update.yml@v1
    secrets:
      token: ${{ secrets.ACTION_TOKEN }}
    with:
      git-name: thoriqhafidz12
      git-email: 111201911729@mhs.dinus.ac.id
      composer-path: ./composer
      branch: composer-update-v1
